### ISSUE TITLE
No such file or directory: 'README.md'

### ISSUE THREAD

**Issue by ykbgbrl** [JWock82/PyNite#113]
Hi, I'm new to python. I'm trying to run the setup.py code on visual studio code but get this error:

No such file or directory: 'README.md'

can somebody please help me? Thanks in advance

**Comment by JWock82** [comment]
One of the first things you'll want to learn with Python is how to install packages. You don't need to do anything with the setup.py file. That is used by PyPI (the Python Packaging Index) to package PyNite so that it can be installed using pip (Python's default package installer). To install PyNite the easy way, go to your computer's command prompt and type `pip install PyNiteFEA`.

If that doesn't work, it's likely because the file path to your Python packages (including pip) is not on your system's PATH environment variable. Give it a try and see if it works. Let me know otherwise.
