### ISSUE TITLE
Error in member3D

### ISSUE THREAD

**Issue by linokl** [JWock82/PyNite#129]
Hi,

I am updating standardsolver with new upgrades in the PyNite (it has been while since I have done the update and adding new features). I am getting the following error:

The error is at this line
phys_member.descritize()

/PyNite/FEModel3D.py", line 3071, in _renumber
AttributeError: 'Member3D' object has no attribute 'descritize'

I am creating the element as follows:

```
element = Member3D(
            name = el_data['element'],
            i_node = get_pynite_node(el_data['start_node'], node_dict),
            j_node = get_pynite_node(el_data['end_node'], node_dict),
            E = E,
            G = G,
            Iy = I_y,
            Iz = I_z,
            J = J,
            A = A,
            model=frame_model,
        )
```
<img width="534" alt="Screenshot 2022-09-14 at 19 33 43" src="https://user-images.githubusercontent.com/20646443/190234826-ef1baff3-31bf-49e3-bce1-fab7c2f43130.png">

I noticed now I have to pass in a new parameter called model, it is not clear exactly what I need to pass in, I have passed in frame_model = FEModel3D()?

I tried to remove this post from the discussions section of github..not sure how to do it. if possible please delete it

Thank you
Lino

**Comment by JWock82** [comment]
You used to pass in the model's load combinations. Now you pass in the model instead and it looks up the load combinations for you. This was changed to correct a slight error in P-Delta member results. The member needs to know what type of analysis was run to return the correct stiffness matrix. A P-Delta analysis requires the member to consider the geometric stiffness matrix.

Thanks,

Craig Brinck
________________________________
From: linokl ***@***.***>
Sent: Wednesday, September 14, 2022 12:15 PM
To: JWock82/PyNite ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [JWock82/PyNite] Error in member3D (Issue #129)


Hi,

I am updating standardsolver with new upgrades in the PyNite (it has been while since I have done the update and adding new features). I am getting the following error:

The error is at this line
phys_member.descritize()

/PyNite/FEModel3D.py", line 3071, in _renumber
AttributeError: 'Member3D' object has no attribute 'descritize'

I am creating the element as follows:

element = Member3D(
            name = el_data['element'],
            i_node = get_pynite_node(el_data['start_node'], node_dict),
            j_node = get_pynite_node(el_data['end_node'], node_dict),
            E = E,
            G = G,
            Iy = I_y,
            Iz = I_z,
            J = J,
            A = A,
            model=frame_model,
        )


I noticed now I have to pass in a parameter called model, is this frame_model = FEModel3D()?

Thank you
Lino

**Comment by JWock82** [comment]
Try this code instead:

element = PhysMember(
            name = el_data['element'],
            i_node = get_pynite_node(el_data['start_node'], node_dict),
            j_node = get_pynite_node(el_data['end_node'], node_dict),
            E = E,
            G = G,
            Iy = I_y,
            Iz = I_z,
            J = J,
            A = A,
            model=frame_model,
        )

You no longer use Members directly. Use Physical Members instead. Physical members descritize themselves into sub-members.

Thanks,

Craig Brinck
________________________________

**Comment by linokl** [comment]
Thank you. It is working perfectly now :)
