### ISSUE TITLE
multiprocessing

### ISSUE THREAD

**Issue by bewegende-Architektur** [JWock82/PyNite#140]
Dear Jwock82,

Wish you a happy new year! hope you are doing well.

Do you think that PyNite could get a multiprocessing-mode?
I have done some quick approach and tried to replace spsolve of scipy with the version of pyparadiso.

FEModel3D.py in line 1952:
`	D1 = spsolve(K11.tocsr(), subtract(subtract(P1, FER1), K12.tocsr() @ D2))`
changed to:
`	D1 = pypardiso.spsolve(K11.tocsr(), subtract(subtract(P1, FER1), K12.tocsr() @ D2))`

This is actually working but does not increase the speed. After running some tests with a large amount of members, i guess the function _renumber at line 3048 in FEModel3D.py is taking more time than the solving itself. This is a another quick approach of adding mp:

```
FEModel3D.py in line 3062:
        # Descritize all the physical members and number each member in the model
        id = 0
        for phys_member in self.Members.values():
            phys_member.descritize()
            for member in phys_member.sub_members.values():
                member.ID = id
                id += 1
```

changed to:
```
        # load mp
        import multiprocessing
        
        # define id as a Value in multiprocessing
        # (all processes need to access this value)
        id = multiprocessing.Value('i', 0)
        
        # pack the previous loop into a function
        def mp_descritize_number(phys_member):
            phys_member.descritize()

            for member in phys_member.sub_members.values():
                member.ID = id.value
                id.value += 1
        
        # list for processes
        processes = []
        
        # create a process for each phys_member, pass phys_member, start and append
        for phys_member in self.Members.values():
            process = multiprocessing.Process(target = mp_descritize_number, args=(phys_member,))
            process.start()
            processes.append(process)
        
        # wait for all the tasks to be done
        for process in processes:
            process.join()
```
Looks like the numbering is working but its leading to a bunch of errors of „Nodal instability“. PyNite is working really fast but its using one core only. Do you think it is possible in general to add multiprocessing?

Greetings,
Chris

**Comment by bewegende-Architektur** [comment]
Ok. I can answer the question: Members and phys_member would need to be also of manager.dict()
Guess this is a huge amount of work. I  will to another quick test ...

**Comment by JWock82** [comment]
This is an interesting idea. I briefly looked into multiprocessing about a year ago. I think it's possible, but a lot of work. Right now the program is pretty fast for most of the models I do. I could see the utility of multiprocessing for very large models with lots of nodes.

I haven't run a profiler on the code since I added physical members, but the slowest part of the code used to be the assembly of the global stiffness matrix. Multiprocessing that would be difficult, since the total matrix is the sum of the member matrices, and you can only add one member matrix at a time to the global matrix. All the matrix operations have to get in a single file line. I suppose you could have multiple global matrices at a time being created, and then add them together at the end in a few operations. I'm sure there's a way to do it. It seems like we'd lose a lot of the simplicity the code currently has, but maybe that's necessary if we ever want to solve really big models with tens of thousands of nodes.

I wouldn't be surprised if descretizing physical members lagged on large models, since each node in the model is checked against each physical member in the model to determine if it lands on that member.

There is definitely room for improving these algorithms to be more efficient. Some of them were put together to just get the job done right, without much thought of efficiency. I am a structural engineer, rather than a programmer. Adding multiprocessing is a matter of profiling the code on a large model to find the choke points, and then figuring out how to feed those processes to multiple cores.

**Comment by bewegende-Architektur** [comment]
Thanks for your quick reply! Totally agree. I was just wondering, if there is an easy approach.
Greetings,
Chris
