### ISSUE TITLE
New release with new array and plotting features?

### ISSUE THREAD

**Issue by connorferster** [JWock82/PyNite#150]
Would you be up for doing a new release that includes the new array and plotting features? I have a bunch of students starting up with PyNite first thing and I am hoping to get the new features included :)

Thanks!

**Comment by JWock82** [comment]
I'll do that. I was planning to release the changes with the new materials feature soon, but I can make them 2 separate releases.

The materials feature is done on my local machine, but it requires me to rework meshing since meshes contained their own material definitions. I'm nearly done with that effort. I think it's for the best, since meshing functions will live in the `FEModel3D` object instead of in a separate module. It'll take fewer lines of code to generate a mesh in the future.

I'm finding the `FEModel3D` class is turning into a behemoth with a lot of similar code throughout. I need to add some helper methods to reduce repetitive code.

**Comment by JWock82** [comment]
I just released it.
