### ISSUE TITLE
Discontinuities in moment, deflection diagrams

### ISSUE THREAD

**Issue by connorferster** [JWock82/PyNite#154]
**Describe the bug**
There seems to be inconsistent results on a beam model. 

1. My checks on the sum of the forces does not seem to check out with the statics check.
2. There seems to discontinuties (steps) in both the moment and deflection diagram which are unexpected. These steps increase in magnitude as the point load is increased.

**To Reproduce**
I have created a gist that shows the model that I am using:
https://gist.github.com/connorferster/e50aff86e552bb6249fde9427af1c095

**Expected behavior**
No steps in moment diagram. No steps in deflection diagram.

**Screenshots**
Images are in the gist.

**Additional context**
I am not sure if I am missing something but there definitely seems to be some strange behaviour going on.

**Comment by JWock82** [comment]
Yikes. I’ll have a look this week. I think I might already know what’s going on. It might be a precision error discrepancy between the user defined load position and the calculated beam length.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Connor Ferster ***@***.***>
Sent: Tuesday, April 4, 2023 1:25:42 AM
To: JWock82/PyNite ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [JWock82/PyNite] Discontinuities in moment, deflection diagrams (Issue #154)


Describe the bug
There seems to be inconsistent results on a beam model.

  1.  My checks on the sum of the forces does not seem to check out with the statics check.
  2.  There seems to discontinuties (steps) in both the moment and deflection diagram which are unexpected. These steps increase in magnitude as the point load is increased.

To Reproduce
I have created a gist that shows the model that I am using:
https://gist.github.com/connorferster/e50aff86e552bb6249fde9427af1c095

Expected behavior
No steps in moment diagram. No steps in deflection diagram.

Screenshots
Images are in the gist.

Additional context
I am not sure if I am missing something but there definitely seems to be some strange behaviour going on.

**Comment by JWock82** [comment]
I've started looking into this. I've confirmed it's a precision error for loads at the end of the beam. Move the load one millimeter to the left and the diagrams look correct. I've got some more digging to do to get to the bottom of it, but at least I know what I'm looking for a little better. I'll keep working at it - should have a fix soon. In the meantime, if you really want the load at the end of the member, I suggest a nodal load instead of a member load.

**Comment by JWock82** [comment]
Just found it! That was easier than I thought. I had introduced this error when I created physical members late last year. Bug squished!!! Look for the fix in v0.0.72. I noticed in your code that you're still defining E and G for each member. Note that you'll need to start using `materials` to use v0.0.72. The updated examples show how to do that. It's pretty painless.

**Comment by connorferster** [comment]
Is it possible that this same bug could have caused a singular matrix?

**Comment by connorferster** [comment]
By the way, the physical members are an excellent feature. So convenient!
