### ISSUE TITLE
Python instructions

### ISSUE THREAD

**Issue by LcnGnd** [JWock82/PyNite#29]
I would like to understand an instruction used in python moduls  inside PyNiteFEA package. I'm talking about this instruction:

**from PyNite.<module_name> import <module_name>**

(in _ init _ .py module)
from PyNite.FEModel3D import FEModel3D

(in FEModel3D.py module)
from PyNite.Node3D import Node3D
from PyNite.Member3D import Member3D
from PyNite.Plate3D import Plate3D

(in Member3D.py module)
from PyNite.BeamSegment import BeamSegment
import PyNite.FixedEndReactions

Why these instructions are use instead of "from PyNite import <module_name>"?
Thanks for help me.

**Comment by JWock82** [comment]
Think of it this way: `from Package.Module import Class`

It's a little confusing because the module name is the same as the class name in our case. Doing it this way allows us to use `Class` directly in our code, instead of `Module.Class` every time.

It's the same as `from numpy.linalg import inv`. If we just did `from numpy import linalg` we'd have to use `linalg.inv` to access the `inv` function.
