### ISSUE TITLE
Explanation of the modules modification

### ISSUE THREAD

**Issue by LcnGnd** [JWock82/PyNite#33]
Can you explain us why was BeamSegment.py modul replaced with two modules divided for direction y and z?

**Comment by JWock82** [comment]
Because the positive internal forces now match the positive local axes, the positive bending sign convention for the y-axis is now different than the z-axis. This is how most commercial programs implement it. I used "class inheritance" to copy the beam segment, and then modified only those parts of it that were different for the y-axis.

**Comment by LcnGnd** [comment]
Thanks, after drawing this convention shouldn't be other misunderstandings
