### ISSUE TITLE
Adding a test suite

### ISSUE THREAD

**Issue by JBloss1517** [JWock82/PyNite#4]
I would like to add some tests to run against the code base. 

The tests would be done using the pytest as the test framework At least initially, the tests would create several different structures and check node reactions and displacements against known values.

The different structures would be examples from structural analysis textbooks, such as R.C. Hibbler's Structural Analysis, to compare the expected results against actual results.  

As far as how this would fit into the overall code structure, the tests would be located in a folder called "tests" in the root directory separate from the source code which would look something like this . . .

* tests
   * test_FEModel
      * conftest.py  ## This is where the different models would be defined as fixtures. These would be here so that they can be used in multiple test cases in different files.
      * test_support_rxn  ## This file is where the different structures support reaction would be checked against expected
      * test_support_displacement ## Similar to test_support_rxn, this would be checking the structure nodes are displacing as expected.

**Comment by JWock82** [comment]
There's a folder in the root directory called "Testing" I recently created for this purpose. I'd recommend placing .py files used for testing in there. If you issue a pull request for your test files I can add them to the project to record testing.

**Comment by JBloss1517** [comment]
What version(s) of python were you wanting to keep the project compatible with? Python 3.6+? If 3.6+, are you okay with f-strings being used instead of string.format?

**Comment by JWock82** [comment]
I haven't really thought of that. I'd like to keep it current. As it's a young project it's easy enough to correct course right now and keep to the latest version of Python.

**Comment by JBloss1517** [comment]
I agree. I have seen a trend in open source projects guaranteeing compatibility with Python 3.6+, so trying to be compatible with anything earlier likely wouldn't be warranted. Then the question is: is bumping up to 3.7 a good idea just yet? While 3.7 does offer some nice features like data classes and has performance boosts, most of the new features can be pip installed to 3.6 environment. Plus this could potentially keep people from wanting to use the project in their project if they are not on the latest version of python. What are your thoughts? Work from a python 3.7 environment, or 3.6 environment?

**Comment by JWock82** [comment]
Let's do 3.6+ then. I'd like to keep this project as mainstream as possible. I'm by no means a coding expert. My primary background is as a structural engineer, and I'm still learning a lot about Python.

**Comment by JBloss1517** [comment]
Sorry I never responded to your last comment. You probably figured I lost interest. I too am a structural engineer and no coding expert. I just enjoy writing code. I'll plan on 3.6 then. I am about finished with the reaction part of the test suite. I have been chipping away on it over my lunch break and haven't been able to work on it as much as I would like to. So far, it has been checking out for single span and two span systems, but for what ever reason in a three span system, the results are deviating from expected. I can issue a pull request of what I have thus far for you to see if you like. Currently in my repo I only have the 1D beams being tested. Locally, I am testing out 2D frames but haven't finished those just yet.

**Comment by JWock82** [comment]
I completely understand. I have a young family to take care of, and can only find a little time here and there to work on this too. I'll take any help I can get. If you do run into an issue, I can usually get it debugged pretty quick. Make sure you're staying up to date with the latest version, since even recently I've found a few bugs that I'm surprised were still in here. I modified this code from 'xlFrame', which I made years ago, and just last week I found a typo that came from translating the VBA into Python. It was causing issues with end-releases. The more tests we run, the more confident I'll be that it's working properly. I've already put it through quite a few tests, but every once in a while I seem to find something unexpected.

**Comment by JWock82** [comment]
Hi @JBloss1517. While running CI for PyNite, I found the latest version of Ubuntu used with Github Actions does not support python 3.6. While Pynite should be compatible with it still, the unittests are no longer being compared anything earlier than 3.7. Just thought I'd let you know since you asked this question a few years back.

**Comment by JBloss1517** [comment]
Thanks for checking! That wouldn't be a problem on my end. I have been using python 3.8 and 3.9 with pynite mostly and have since abandoned efforts to create a solid test suite due to time (lack thereof).
